version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
            MYSQL_DATABASE: book
            MYSQL_USER: user
            MYSQL_PASSWORD: 
        ports:
            - "9906:3306"